### ISSUE TITLE
Retrieve data of previously added items

### ISSUE THREAD

**Issue by ElSebita** [rh-id/a-personal-stuff#5]
Little nice app for pantry.
I added cans of same brand and type using barcode. It would be great to retrieve and reuse previous data based on same barcode to save on typing.

**Comment by rh-id** [comment]
Will add Auto complete text on the barcode field so it will suggest previously added barcode.

**Comment by rh-id** [comment]
This is available on the next release

**Comment by ElSebita** [comment]
Still not implemented hmmm

**Comment by rh-id** [comment]
hi, it was there at the latest version. after adding item with barcode (example: 123), the suggestion will appear for the next item

**Comment by ElSebita** [comment]
I don't want to bother but it's not working.
v1.3
![Screenshot_20230726-133201.png](https://github.com/rh-id/a-personal-stuff/assets/7228356/cc868ca5-8647-40bc-903f-9dba9043ec2b)

Then scanning the same:
![Screenshot_20230726-133153.png](https://github.com/rh-id/a-personal-stuff/assets/7228356/130eaae2-909c-4834-9852-3a26c1462a23)
